version: '3.8'
services:
  build:
    platform: linux/amd64
    build:
      context: .
    container_name: keyball-build-container
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash build.sh
